### ISSUE TITLE
1.9 Crash Report :( 

### ISSUE THREAD

**Issue by RebeccaRedstone** [nfinit-gaming/BetterAgriculture#2]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-18.jar)
  LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  ProgressionTransformer (Progression-1.9-0.5.2.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.59-universal.jar)
  Player Stats Core (PlayerStats_1.9-1.1.0.jar)
  CCCDeobfPlugin (unknown)
  ShetiPhian-ASM (shetiphiancore-1.9.0-3.2.5.jar)
  BetterFoliageLoader (BetterFoliage-MC1.9-2.0.11.jar)
  MalisisCorePlugin (malisiscore-1.9-3.0.6.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.9-2.0.5.jar)
  CCLCorePlugin (CodeChickenLib-1.9-2.0.1.29-universal.jar)
  LoadingPlugin (FastLeafDecay-MC1.9-1.2.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 11/06/16 7:04 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: betteragriculture/world/biome/BaseBiome
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:553)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:210)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:434)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: betteragriculture/world/biome/BaseBiome
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:469)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:522)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: betteragriculture.world.biome.BaseBiome
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 35 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/biome/Biome
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 37 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.biome.Biome
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 41 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 3808879872 bytes (3632 MB) / 4260102144 bytes (4062 MB) up to 4260102144 bytes (4062 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmx4096M -Xms4096M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.23 Powered by Forge 12.16.1.1934 80 mods loaded, 80 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.1.1934.jar) 
    UC  Forge{12.16.1.1934} [Minecraft Forge](forge-1.9-12.16.1.1934.jar) 
    UC  buildingbrickshooks{1.9-2.0.5} [Building Bricks Hooks](minecraft.jar) 
    UC  CodeChickenCore{2.0.1.59} [CodeChicken Core](minecraft.jar) 
    UC  playerstatscore{1.1.0} [Player Stats Core](minecraft.jar) 
    UC  JEI{3.3.3.200} [Just Enough Items](jei_1.9-3.3.3.200 %281%29.jar) 
    UC  abyssalcraft{1.9.1.6} [AbyssalCraft](AbyssalCraft-1.9-1.9.1.6.jar) 
    UC  animalbikes{1.8} [Animal Bikes](AnimalBikes_1.9.0%2826mar16%29.jar) 
    UC  AnimalsPlus{1.7} [Animals Plus](AnimalsPlus-1.8.jar) 
    UC  basemetals{2.2.2} [Base Metals](BaseMetals_1.9-2.2.2.jar) 
    UC  Baubles{1.2.0.2} [Baubles](Baubles-1.9-1.2.0.2.jar) 
    UE  betteragriculture{0.13} [Better Agriculture](BetterAgriculture_1.9-0.13.jar) 
    UC  BetterFoliage{2.0.11} [Better Foliage](BetterFoliage-MC1.9-2.0.11.jar) 
    UC  BiomesOPlenty{4.0.2.2018} [Biomes O' Plenty](BiomesOPlenty-1.9-4.0.2.2018-universal.jar) 
    UC  BloodMagic{1.9-2.0.0-38} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9-2.0.0-38.jar) 
    UC  Botania{r1.8-305} [Botania](Botania-unofficial.r1.8-305.jar) 
    UC  Quark{beta-18} [Quark](Quark-beta-18.jar) 
    UC  buildingbricks{1.9-2.0.5} [Building Bricks](BuildingBricks-1.9-2.0.5.jar) 
    UC  Chameleon{1.9-2.1.3} [Chameleon](Chameleon-1.9-2.1.3.jar) 
    UC  Chimneys{1.9} [Chimneys](Chimneys-1.9-3.jar) 
    UC  chisel{@VERSION@} [Chisel](Chisel-MC1.9-0.0.4.14.jar) 
    UC  chiselsandbits{9.18} [Chisels & Bits](chiselsandbits-9.18.jar) 
    UC  decorationmegapack{1.9.4} [Decoration Mega Pack](decorationmegapack-19410009775.zip) 
    UC  enchiridion{3.1.1} [Enchiridion](Enchiridion-1.9-3.1.1.jar) 
    UC  enderutilities{0.6.0} [Ender Utilities](enderutilities-1.9-0.6.0.jar) 
    UC  EnderZoo{1.9-1.2.1.39} [Ender Zoo](EnderZoo-1.9-1.2.1.39.jar) 
    UC  excore{1.5.3} [EXCore](Excore-1.5.3-1.9.jar) 
    UC  ezstorage{1.0} [EZ Storage](ezstorage-1.9-1.2.1.jar) 
    UC  ezextended{1.0.1} [EZ Extended](ezextended-1.0.1-[1.9].jar) 
    UC  FastLeaveDecay{1.1} [Fast Leave Decay](FastLeafDecay-MC1.9-1.2.jar) 
    UC  substratum{1.3.0.0} [Substratum](Substratum-1.9-1.3.0.0.jar) 
    UC  foundry{2.0.0.0-alpha3} [Foundry](Foundry-1.9-2.0.0.0-alpha3.jar) 
    UC  lit{1.9-1.0.15} [Little Insignificant Things](LittleInsignificantThings-1.9-1.0.15.jar) 
    UC  SilentLib{1.0.7} [Silent Lib](SilentLib-1.9-1.0.7-13.jar) 
    UC  SilentGems{2.0.11} [Silent's Gems](SilentsGems-1.9-2.0.11-29.jar) 
    UC  gemulation{1.9-2.0.6} [Gemulation](gemulation-1.9-2.0.6.jar) 
    UC  grapple_hooks{1.0.8} [Grapple Hooks](Grapple Hooks-1.9-1.0.8.jar) 
    UC  InventoryPets{1.4.6} [Inventory Pets](inventorypets-1.4.6.jar) 
    UC  IronChest{6.0.133.777} [Iron Chest](ironchest-1.9-6.0.133.777.jar) 
    UC  fyberbackpack{1.0.1} [Just Backpacks](justbackpacks-mc1.9-1.0.1.jar) 
    UC  jet_packs{1.0.0} [Just JetPacks](JustJetpacks-1.0.0.jar) 
    UC  lteleporters{1.1.1} [Lemon's Simple Teleporters](LemonsSimpleTeleporters-1.1.1.jar) 
    UC  Lux{1.5.0} [Lux](Lux-1.9-1.5.0.jar) 
    UC  malisiscore{1.9-3.0.6} [MalisisCore](malisiscore-1.9-3.0.6.jar) 
    UC  malisisblocks{1.9-3.0.1} [Malisis Blocks](malisisblocks-1.9-3.0.1.jar) 
    UC  malisisdoors{1.9-4.0.1} [MalisisDoors](malisisdoors-1.9-4.0.1.jar) 
    UC  mantle{1.9-0.10.1.jenkins141} [Mantle](Mantle-1.9-0.10.1.jar) 
    UC  MapWriter{2.4.19} [MapWriter](MapWriter-1.9-2.4.19.jar) 
    UC  RadixCore{1.9-2.1.0} [RadixCore](RadixCore-1.9-2.1.0-universal.jar) 
    UC  MCA{1.9-5.1.3} [Minecraft Comes Alive](MCA-1.9-5.1.3-universal.jar) 
    UC  modernmetals{0.9.2.3} [Modern Metals](ModernMetals-0.9.2.3.jar) 
    UC  moon-core{2.0} [Moon's Core](MoonCore%282.0%29 1.9.jar) 
    UC  shetiphiancore{3.2.5} [ShetiPhian-Core](shetiphiancore-1.9.0-3.2.5.jar) 
    UC  multibeds{1.1.1} [Multi-Beds](multibeds-1.9.0-1.1.1.jar) 
    UC  terraqueous{1.1.2.2} [Terraqueous](terraqueous-1.9.0-1.1.2.2.jar) 
    UC  multistorage{1.1.1.1} [Multi-Storage](multistorage-1.9.0-1.1.1.1.jar) 
    UC  nethercore{1.9-2.0.1} [Nether Core](nethercore-1.9-2.0.1.jar) 
    UC  harvestcraft{1.9a} [Pam's HarvestCraft](Pam's HarvestCraft 1.9b.jar) 
    UC  pattysmoretools{1.0} [PattysMoreTools](PattysMoreTools2-1.9-1.1.jar) 
    UC  plantmegapack{1.9.8} [Plant Mega Pack](plantmegapack-19810001118.zip) 
    UC  playerstats{1.1.0} [Player Stats](PlayerStats_1.9-1.1.0.jar) 
    UC  progression{0.5.2} [Progression](Progression-1.9-0.5.2.jar) 
    UC  progressiveautomation{1.6.44} [Progressive Automation](ProgressiveAutomation-1.9-1.6.44.jar) 
    UC  RandomUtilities{3.0.2} [Random Utilities](Random Utilities-1.9-3.0.3.jar) 
    UC  randomthings{3.7} [Random Things](RandomThings-MC1.9-3.7.jar) 
    UC  xreliquary{1.9-1.3.2.369} [Reliquary](Reliquary-1.9-1.3.2.369.jar) 
    UC  rftools{4.48} [RFTools](rftools-1.9.0-4.48.jar) 
    UC  rftoolsdim{4.23beta38} [RFTools Dimensions](rftoolsdim-1.9.0-4.23beta38.jar) 
    UC  RTG{1.9-2.0.0-alpha.4} [Realistic Terrain Generation](RTG-1.9-2.0.0-alpha.4.jar) 
    UC  SGExtraParts{1.0.0} [Silent's Gems: Extra Parts](SGExtraParts-1.9-1.0.0-1.jar) 
    UC  soggytransportation{1.9-RB2} [§bSoggyMustache's Transportation](soggytransportation-17.0.0%281.9%29.jar) 
    UC  soulshardstow{1.9-2.3.10-26} [Soul Shards - The Old Ways](SoulShards-TOW-1.9-2.3.10-26.jar) 
    UC  StorageDrawers{1.9-3.1.6} [Storage Drawers](StorageDrawers-1.9-3.1.6.jar) 
    UC  tconstruct{1.9-2.3.1.jenkins227} [Tinkers' Construct](TConstruct-1.9-2.3.1a.jar) 
    UC  TinkersAddons{1.0.1} [Tinkers' Addons](Tinkers' Addons-1.9-1.0.1.jar) 
    UC  ultimate_unicorn_mod{1.4.15} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!](ultimate_unicorn_mod-1.9-1.4.15.jar) 
    UC  vending{1.3.1} [vending](vending-1.9-1.3.4.jar) 
    UC  Waila{1.7.0} [Waila](Waila-1.7.0-B2_1.9 %282%29.jar) 
    UC  WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.9-1.1.7 %281%29.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-18.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  lumien.randomthings.asm.ClassTransformer
ProgressionTransformer (Progression-1.9-0.5.2.jar)
  joshie.progression.asm.ProgressionTransformer
CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.59-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
Player Stats Core (PlayerStats_1.9-1.1.0.jar)
  mrdimka.playerstats.core.CoreClassTransformer
CCCDeobfPlugin (unknown)

ShetiPhian-ASM (shetiphiancore-1.9.0-3.2.5.jar)
  shetiphian.core.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.9-2.0.11.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
MalisisCorePlugin (malisiscore-1.9-3.0.6.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
LoadingPluginBuildingBricks (BuildingBricks-1.9-2.0.5.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
CCLCorePlugin (CodeChickenLib-1.9-2.0.1.29-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
LoadingPlugin (FastLeafDecay-MC1.9-1.2.jar)
  lumien.fastleavedecay.asm.ClassTransformer
    GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 10.18.15.4281' Renderer: 'Intel(R) HD Graphics 520'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)

**Comment by knoxhack** [comment]
1.9 port coming soon

**Comment by knoxhack** [comment]
Backport to 1.9 uploaded to Curse get it here: http://minecraft.curseforge.com/projects/better-agriculture/files
