### ISSUE TITLE
Error registering items to Ore Dictionary

### ISSUE THREAD

**Issue by CatastropheBlack** [nfinit-gaming/BetterAgriculture#57]
Using MC 1.12.2, Forge 14.23.3.2655, Better Ag 1.2.3
```
[18:39:31] [main/WARN] [FML]: ****************************************
[18:39:31] [main/WARN] [FML]: * A broken ore dictionary registration with name leather has occurred. It adds an item (type: class com.knoxhack.betteragriculture.items.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Better Agriculture report it to them!
[18:39:31] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:668)
[18:39:31] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:640)
[18:39:31] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:638)
[18:39:31] [main/WARN] [FML]: *  at com.knoxhack.betteragriculture.init.Recipes.addOreRegistration(Recipes.java:22)
[18:39:31] [main/WARN] [FML]: *  at com.knoxhack.betteragriculture.init.Recipes.init(Recipes.java:9)
[18:39:31] [main/WARN] [FML]: *  at com.knoxhack.betteragriculture.proxy.CommonProxy.preInit(CommonProxy.java:32)...
[18:39:31] [main/WARN] [FML]: ****************************************
[18:39:31] [main/WARN] [FML]: ****************************************
[18:39:31] [main/WARN] [FML]: * A broken ore dictionary registration with name leather has occurred. It adds an item (type: class com.knoxhack.betteragriculture.items.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Better Agriculture report it to them!
[18:39:31] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:668)
[18:39:31] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:640)
[18:39:31] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:638)
[18:39:31] [main/WARN] [FML]: *  at com.knoxhack.betteragriculture.init.Recipes.addOreRegistration(Recipes.java:23)
[18:39:31] [main/WARN] [FML]: *  at com.knoxhack.betteragriculture.init.Recipes.init(Recipes.java:9)
[18:39:31] [main/WARN] [FML]: *  at com.knoxhack.betteragriculture.proxy.CommonProxy.preInit(CommonProxy.java:32)...
[18:39:31] [main/WARN] [FML]: ****************************************
[18:39:31] [main/WARN] [FML]: ****************************************
[18:39:31] [main/WARN] [FML]: * A broken ore dictionary registration with name leather has occurred. It adds an item (type: class com.knoxhack.betteragriculture.items.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Better Agriculture report it to them!
[18:39:31] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:668)
[18:39:31] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:640)
[18:39:31] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:638)
[18:39:31] [main/WARN] [FML]: *  at com.knoxhack.betteragriculture.init.Recipes.addOreRegistration(Recipes.java:24)
[18:39:31] [main/WARN] [FML]: *  at com.knoxhack.betteragriculture.init.Recipes.init(Recipes.java:9)
[18:39:31] [main/WARN] [FML]: *  at com.knoxhack.betteragriculture.proxy.CommonProxy.preInit(CommonProxy.java:32)...
[18:39:31] [main/WARN] [FML]: ****************************************
[18:39:31] [main/WARN] [FML]: ****************************************
[18:39:31] [main/WARN] [FML]: * A broken ore dictionary registration with name feather has occurred. It adds an item (type: class com.knoxhack.betteragriculture.items.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Better Agriculture report it to them!
[18:39:31] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:668)
[18:39:31] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:640)
[18:39:31] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:638)
[18:39:31] [main/WARN] [FML]: *  at com.knoxhack.betteragriculture.init.Recipes.addOreRegistration(Recipes.java:25)
[18:39:31] [main/WARN] [FML]: *  at com.knoxhack.betteragriculture.init.Recipes.init(Recipes.java:9)
[18:39:31] [main/WARN] [FML]: *  at com.knoxhack.betteragriculture.proxy.CommonProxy.preInit(CommonProxy.java:32)...
[18:39:31] [main/WARN] [FML]: ****************************************
```

**Comment by dshadowwolf** [comment]
This generally means that the mod is trying to register an OreDictionary during the FMLPreInitializationEvent - which, for versions prior to 1.12, was the proper time and place to do it. 1.12 and later it should be done during the earliest possible point - in this case RegistryEvent.Register<Item>... @knoxhack if you need some help, I'm always available.
